### LOGIN - USUÁRIO COMUM
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "teste",
  "senha": "teste123"
}

### [COMMON USER] Upload documento para funcionário 1
POST http://localhost:8080/funcionarios/1/documentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5vbWUiOiJhZG1pbiIsInBlcmZpbCI6ImFkbWluIiwiaXNzIjoiQXV0b0dSSCIsInN1YiI6IjEiLCJleHAiOjE3NTY0NDg2OTYsImlhdCI6MTc1NjQyNzA5Nn0.whSu8ltkYfSv3KX-MGCMpxTG5bFYc3Set4PViRwcVmA
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="teste.pdf"
Content-Type: application/pdf

< ./teste.pdf
------WebKitFormBoundary--

### [COMMON USER] Listar documentos do funcionário 1
GET http://localhost:8080/funcionarios/1/documentos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5vbWUiOiJhZG1pbiIsInBlcmZpbCI6ImFkbWluIiwiaXNzIjoiQXV0b0dSSCIsInN1YiI6IjEiLCJleHAiOjE3NTYzMTA0MDAsImlhdCI6MTc1NjMwMDk0OX0.La8bEfanveMPYX5FMsV8sgVdy47hIlIStWXw_RWNd3M

---

### LOGIN - ADMIN
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "login": "admin",
  "senha": "adm123"
}

### [ADMIN] Listar todos os documentos
GET http://localhost:8080/documentos
Authorization: Bearer {{ADMIN_TOKEN}}

### [ADMIN] Download documento ID 1
GET http://localhost:8080/documentos/2/download
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5vbWUiOiJhZG1pbiIsInBlcmZpbCI6ImFkbWluIiwiaXNzIjoiQXV0b0dSSCIsInN1YiI6IjEiLCJleHAiOjE3NTYzMTA0MDAsImlhdCI6MTc1NjMwMDk0OX0.La8bEfanveMPYX5FMsV8sgVdy47hIlIStWXw_RWNd3M

### [ADMIN] Deletar documento ID 2
DELETE http://localhost:8080/documentos/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOjEsIm5vbWUiOiJhZG1pbiIsInBlcmZpbCI6ImFkbWluIiwiaXNzIjoiQXV0b0dSSCIsInN1YiI6IjEiLCJleHAiOjE3NTYzMTA0MDAsImlhdCI6MTc1NjMwMDk0OX0.La8bEfanveMPYX5FMsV8sgVdy47hIlIStWXw_RWNd3M

### [ADMIN] Listar documentos novamente (confirma exclusão)
GET http://localhost:8080/documentos
Authorization: Bearer {{ADMIN_TOKEN}}
